### ISSUE TITLE
Retreive_key does not work

### ISSUE THREAD

**Issue by DamianPe** [AdamStrojek/libetrv#10]
Hi Adam,

Retreive secret key from eTRV device seems not to be working.

```
pi@bridge01:~/libetrv$ python3 -m libetrv.cli device 00:04:2f:6a:f2:9a retrive_key
In 5 seconds this script will try to retrieve a secure key from eTRV device. Don't forget to save it for later. Before that be sure that device is in pairing mode. You can achieve that by pressing button on device
2019-12-03 18:14:09.463 | DEBUG    | libetrv.device:connect:53 - Trying connect to 00:04:2f:6a:f2:9a
2019-12-03 18:14:11.279 | DEBUG    | libetrv.device:send_pin:77 - Write PIN to 00:04:2f:6a:f2:9a
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/libetrv/libetrv/cli.py", line 76, in <module>
    fire.Fire(CLI)
  File "/home/pi/.local/lib/python3.5/site-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/pi/.local/lib/python3.5/site-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/home/pi/.local/lib/python3.5/site-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/pi/libetrv/libetrv/cli.py", line 47, in retrive_key
    print("Secret Key:", self._device.secret_key)
  File "/home/pi/libetrv/libetrv/properties.py", line 22, in __get__
    return self.get_data_object(device).retrieve()
  File "/home/pi/libetrv/libetrv/properties.py", line 61, in retrieve
    return self.retrieve_object(self.device)
  File "/home/pi/libetrv/libetrv/properties.py", line 124, in retrieve_object
    return getattr(self, self.get_direct_field())
  File "/home/pi/libetrv/libetrv/properties.py", line 120, in get_direct_field
    raise AttributeError('Field direct field should be defined')
AttributeError: Field direct field should be defined
```
Do you have any idea what can be wrong?

For the future, please don't close issue just after your response, you shall wait for a confirmation from user who submitted an issue that problem is solved or not :)

Regards
Damian

**Comment by AdamStrojek** [comment]
Hi Damian,

Thanks for reporting this issue. The stack trace you provided was very helpful. Now I think it should be resolved, please try the newest version of library from `master` branch. I hope it solves your problem.

In the previous issue, you were reporting missing possibility to obtain a secret key from the device that was not correct, so I have closed that issue. It is implemented and was exposed in CLI. Also as far as I remember, but this may be true only for team members on GitHub, you can still comment even in closed ticket and I would reopen it. Please remember to keep one issue per ticket, it is much easier to manage them and keep track of what was already reported and fixed.

Please report back did this fixed your problem.

Best,
Adam

**Comment by DamianPe** [comment]
Hi Adam,

Thank you for response and code update.
I confirm, now it works perfectly, secret key is obtained.

Damian
