### ISSUE TITLE
retrieve-key problem

### ISSUE THREAD

**Issue by k3s4** [AdamStrojek/libetrv#22]
Hello,

I have following issue with connecting to my Danfoss ECO thermostat:

> root@raspberrypi:~/libetrv# python3 -m libetrv.cli - device 00:04:2f:67:08:10 retrieve-key
In 5 seconds this script will try to retrieve a secure key from eTRV device. Don't forget to save it for later. Before that be sure that device is in pairing mode. You can achieve that by pressing button on device
2020-05-07 19:01:11.847 | DEBUG    | libetrv.device:connect:54 - Trying connect to 00:04:2f:67:08:10
2020-05-07 19:01:16.111 | DEBUG    | libetrv.device:send_pin:84 - Write PIN to 00:04:2f:67:08:10
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/libetrv/libetrv/cli.py", line 79, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/root/libetrv/libetrv/cli.py", line 47, in retrieve_key
    print("Secret Key:", self._device.secret_key)
  File "/root/libetrv/libetrv/properties.py", line 22, in __get__
    return self.get_data_object(device).retrieve()
  File "/root/libetrv/libetrv/properties.py", line 59, in retrieve
    self.read()
  File "/root/libetrv/libetrv/properties.py", line 91, in read
    data = etrv_read_data(self.device, handler, send_pin, use_encoding)
  File "/root/libetrv/libetrv/utils.py", line 13, in etrv_read_data
    device.connect(send_pin)
  File "/root/libetrv/libetrv/device.py", line 65, in connect
    self.send_pin()
  File "/root/libetrv/libetrv/device.py", line 86, in send_pin
    self.ble_device.writeCharacteristic(pin_handler, self.pin, True)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 543, in writeCharacteristic
    return self._getResp('wr')
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.7/dist-packages/bluepy/btle.py", line 368, in _waitResp
    raise BTLEGattError("Bluetooth command failed", resp)
bluepy.btle.BTLEGattError: Bluetooth command failed (code: 14, error: Request attribute has encountered an unlikely error)

> root@raspberrypi:~# python3 --version
> Python 3.7.3

any idea what is wrong? 

Thanks for help :)

**Comment by k3s4** [comment]
sorry - problem was because another process was using bluetooth..
issue can be closed
