### ISSUE TITLE
Error in CLI btle.BTLEDisconnectError

### ISSUE THREAD

**Issue by kajaba** [AdamStrojek/libetrv#24]
Hello, i tried to use this library and using:
`sudo python3 -m libetrv.cli device 00:04:2F:44:78:26 battery`
i got an error:
```
2020-10-13 11:19:45.608 | DEBUG    | libetrv.device:connect:54 - Trying connect to 00:04:2F:44:78:26
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/libetrv/device.py", line 63, in connect
    self.ble_device = btle.Peripheral(self.address)
AttributeError: 'NoneType' object has no attribute 'Peripheral'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/libetrv/cli.py", line 79, in <module>
    fire.Fire(CLI)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/usr/local/lib/python3.7/dist-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/libetrv/cli.py", line 54, in settings
    result = self._device.settings
  File "/usr/local/lib/python3.7/dist-packages/libetrv/properties.py", line 22, in __get__
    return self.get_data_object(device).retrieve()
  File "/usr/local/lib/python3.7/dist-packages/libetrv/properties.py", line 59, in retrieve
    self.read()
  File "/usr/local/lib/python3.7/dist-packages/libetrv/properties.py", line 91, in read
    data = etrv_read_data(self.device, handler, send_pin, use_encoding)
  File "/usr/local/lib/python3.7/dist-packages/libetrv/utils.py", line 13, in etrv_read_data
    device.connect(send_pin)
  File "/usr/local/lib/python3.7/dist-packages/libetrv/device.py", line 67, in connect
    except btle.BTLEDisconnectError:
AttributeError: 'NoneType' object has no attribute 'BTLEDisconnectError'
```
Can you please direct me, what might be wrong? I am a newbie with python
Thanks

**Comment by AdamStrojek** [comment]
It looks like there are some issues with btle library. Did you install all requirements?

**Comment by AdamStrojek** [comment]
Closing due to no response
