### ISSUE TITLE
error cli on rpi

### ISSUE THREAD

**Issue by minscof** [AdamStrojek/libetrv#7]
Thanks for your code. I bought a danfoss eco valve, and I try to manage it.
When I launch the scan in root, I have this error

> (libetrv) root@rpiA-parents:/home/pi/libetrv# python3 -m libetrv.cli scan
Detected eTRV devices:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/libetrv/libetrv/cli.py", line 76, in <module>
    fire.Fire(CLI)
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/fire/core.py", line            127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/fire/core.py", line            366, in _Fire
    component, remaining_args)
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/fire/core.py", line            542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "/home/pi/libetrv/libetrv/cli.py", line 22, in scan
    for device in eTRVDevice.scan(timeout):
  File "/home/pi/libetrv/libetrv/device.py", line 37, in scan
    devices = btle.Scanner().scan(timeout)
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/bluepy/btle.py", lin           e 852, in scan
    self.start(passive=passive)
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/bluepy/btle.py", lin           e 797, in start
    self._mgmtCmd(self._cmd()+"end")
  File "/home/pi/venv/libetrv/lib/python3.5/site-packages/bluepy/btle.py", lin           e 312, in _mgmtCmd
    raise BTLEManagementError("Failed to execute management command '%s'" % (c           md), rsp)
bluepy.btle.BTLEManagementError: Failed to execute management command 'scanend           ' (code: 11, error: Rejected)

Can you help ?

**Comment by AdamStrojek** [comment]
Hi,
It sounds like you do not have sufficient permissions to perform this action. Start this as root or follow guide in README

**Comment by minscof** [comment]
Thanks for your answer, but I already ran the command as root.

So I searched on google and I find this [post](https://github.com/IanHarvey/bluepy/issues/150#issuecomment-562848132) with the same error, the proposed fix was to add "passive=True" in th btle.Scanner().scan(timeout).
I tried, and the error disapperead but the trv has not be found. Is there something else to do to detect it ?

**Comment by minscof** [comment]
I increase the timeout value and I stop another processus that was using the bluetooth dongle, and it works now.

I close the issue

**Comment by AdamStrojek** [comment]
I have also noticed that only one device can access Bluetooth, this is a common problem and I do not know any solution for that.
